import type { InventoryStock, Machine, SparePart } from "@/types"

export const LOCAL_MACHINE_SEED: Machine[] = [
  {
    id: "local-scaffold-1",
    name: "Andamio tubular",
    model: "estándar obra",
    category: "scaffold",
    status: "available",
    locationType: "deposito",
    location: null,
    rental: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "local-scaffold-2",
    name: "Andamio modular",
    model: "marco europeo",
    category: "scaffold",
    status: "available",
    locationType: "deposito",
    location: null,
    rental: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "local-scaffold-3",
    name: "Andamio pasillero",
    model: "pasarela 1.5m",
    category: "scaffold",
    status: "maintenance",
    locationType: "taller",
    location: null,
    rental: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]

export const LOCAL_STOCK_SEED: InventoryStock[] = [
  {
    id: "local-stock-riendas-largas",
    name: "Riendas",
    category: "riendas",
    unit: "unidad",
    stockTotal: 100,
    stockAvailable: 100,
    stockRented: 0,
    subtype: null,
    size: "largas",
    locationType: "deposito",
    source: "manual",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "local-stock-riendas-cortas",
    name: "Riendas",
    category: "riendas",
    unit: "unidad",
    stockTotal: 100,
    stockAvailable: 100,
    stockRented: 0,
    subtype: null,
    size: "cortas",
    locationType: "deposito",
    source: "manual",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "local-stock-puntales-3m",
    name: "Puntales",
    category: "puntales",
    unit: "unidad",
    stockTotal: 100,
    stockAvailable: 100,
    stockRented: 0,
    subtype: null,
    size: "3m",
    locationType: "deposito",
    source: "manual",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "local-stock-tablones-3m",
    name: "Tablones",
    category: "andamio_accesorios",
    unit: "unidad",
    stockTotal: 100,
    stockAvailable: 100,
    stockRented: 0,
    subtype: null,
    size: "3m",
    locationType: "deposito",
    source: "manual",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]

export const LOCAL_SPARE_PART_SEED: SparePart[] = [
  {
    id: "local-part-1",
    machineId: "local-scaffold-1",
    machineName: "Andamio tubular",
    machineModel: "estándar obra",
    partName: "Bulón",
    partCode: "SCAF-BUL-01",
    category: "estructural",
    unit: "unidad",
    stockTotal: 12,
    stockAvailable: 12,
    stockUsed: 0,
    source: "manual",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "local-part-2",
    machineId: "local-scaffold-1",
    machineName: "Andamio tubular",
    machineModel: "estándar obra",
    partName: "Traba",
    partCode: "SCAF-TRA-01",
    category: "estructural",
    unit: "unidad",
    stockTotal: 8,
    stockAvailable: 8,
    stockUsed: 0,
    source: "manual",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]
