var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(protected)/rentals/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0y9verv._.js")
R.c("server/chunks/ssr/node_modules_0ev7kv1._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_1iamx_5.js")
R.c("server/chunks/ssr/[root-of-the-server]__09vvflu._.js")
R.c("server/chunks/ssr/node_modules_0yjqtz1._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1-3axf8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0-o-goa.js")
R.c("server/chunks/ssr/src_app_(protected)_layout_tsx_07oa7uc._.js")
R.c("server/chunks/ssr/_next-internal_server_app_(protected)_rentals_page_actions_1f9w4n3.js")
R.m(1098)
module.exports=R.m(1098).exports
