// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/andamios" | "/dashboard" | "/inventory" | "/inventory-movements" | "/inventory/[id]" | "/inventory/new" | "/login" | "/machines" | "/machines/[id]" | "/machines/[id]/blueprints" | "/machines/[id]/parts" | "/machines/new" | "/maintenance" | "/rentals" | "/rentals/[id]" | "/rentals/new" | "/repairs" | "/repairs/[id]" | "/repairs/new" | "/stock" | "/stock-movements"
type AppRouteHandlerRoutes = "/api/cloudinary/delete" | "/api/sync-3c" | "/api/sync-3c/agent-status" | "/api/sync-3c/status"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/andamios": {}
  "/api/cloudinary/delete": {}
  "/api/sync-3c": {}
  "/api/sync-3c/agent-status": {}
  "/api/sync-3c/status": {}
  "/dashboard": {}
  "/inventory": {}
  "/inventory-movements": {}
  "/inventory/[id]": { "id": string; }
  "/inventory/new": {}
  "/login": {}
  "/machines": {}
  "/machines/[id]": { "id": string; }
  "/machines/[id]/blueprints": { "id": string; }
  "/machines/[id]/parts": { "id": string; }
  "/machines/new": {}
  "/maintenance": {}
  "/rentals": {}
  "/rentals/[id]": { "id": string; }
  "/rentals/new": {}
  "/repairs": {}
  "/repairs/[id]": { "id": string; }
  "/repairs/new": {}
  "/stock": {}
  "/stock-movements": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
