// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../src/app/(protected)/andamios/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/andamios">> = Specific
  const handler = {} as typeof import("../../../src/app/(protected)/andamios/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(protected)/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../../src/app/(protected)/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(protected)/inventory-movements/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/inventory-movements">> = Specific
  const handler = {} as typeof import("../../../src/app/(protected)/inventory-movements/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(protected)/inventory/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/inventory/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/(protected)/inventory/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(protected)/inventory/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/inventory/new">> = Specific
  const handler = {} as typeof import("../../../src/app/(protected)/inventory/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(protected)/inventory/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/inventory">> = Specific
  const handler = {} as typeof import("../../../src/app/(protected)/inventory/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(protected)/machines/[id]/blueprints/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/machines/[id]/blueprints">> = Specific
  const handler = {} as typeof import("../../../src/app/(protected)/machines/[id]/blueprints/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(protected)/machines/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/machines/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/(protected)/machines/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(protected)/machines/[id]/parts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/machines/[id]/parts">> = Specific
  const handler = {} as typeof import("../../../src/app/(protected)/machines/[id]/parts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(protected)/machines/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/machines/new">> = Specific
  const handler = {} as typeof import("../../../src/app/(protected)/machines/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(protected)/machines/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/machines">> = Specific
  const handler = {} as typeof import("../../../src/app/(protected)/machines/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(protected)/maintenance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/maintenance">> = Specific
  const handler = {} as typeof import("../../../src/app/(protected)/maintenance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(protected)/rentals/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/rentals/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/(protected)/rentals/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(protected)/rentals/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/rentals/new">> = Specific
  const handler = {} as typeof import("../../../src/app/(protected)/rentals/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(protected)/rentals/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/rentals">> = Specific
  const handler = {} as typeof import("../../../src/app/(protected)/rentals/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(protected)/repairs/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/repairs/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/(protected)/repairs/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(protected)/repairs/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/repairs/new">> = Specific
  const handler = {} as typeof import("../../../src/app/(protected)/repairs/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(protected)/repairs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/repairs">> = Specific
  const handler = {} as typeof import("../../../src/app/(protected)/repairs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(protected)/stock-movements/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/stock-movements">> = Specific
  const handler = {} as typeof import("../../../src/app/(protected)/stock-movements/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(protected)/stock/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/stock">> = Specific
  const handler = {} as typeof import("../../../src/app/(protected)/stock/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/cloudinary/delete/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cloudinary/delete">> = Specific
  const handler = {} as typeof import("../../../src/app/api/cloudinary/delete/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/sync-3c/agent-status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sync-3c/agent-status">> = Specific
  const handler = {} as typeof import("../../../src/app/api/sync-3c/agent-status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/sync-3c/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sync-3c">> = Specific
  const handler = {} as typeof import("../../../src/app/api/sync-3c/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/sync-3c/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sync-3c/status">> = Specific
  const handler = {} as typeof import("../../../src/app/api/sync-3c/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../src/app/(protected)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/(protected)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
